# This is a basic workflow to help you get started with Actions

name: BuildPDFs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          Add-type -AssemblyName office -ErrorAction SilentlyContinue
          Add-Type -AssemblyName microsoft.office.interop.powerpoint -ErrorAction SilentlyContinue

          $sourceFilesDir = ".\src"
          $outputFileDir = ".\bin" 

          if(Test-Path $outputFileDir){
              Remove-Item $outputFileDir -Force -Recurse
          }

          New-Item -ItemType Directory $outputFileDir

          $ppt = New-Object -com powerpoint.application
          $opt = [Microsoft.Office.Interop.PowerPoint.PpSaveAsFileType]::ppSaveAsPDF
          Get-ChildItem $sourceFilesDir -Filter '*.pptx' | ForEach-Object {
              $srcFileName = $_.Name
              $outFileName = $srcFileName -replace (".pptx", ".pdf")
              $srcFile = $_.FullName
              $outFile = Join-Path -Path $outputFileDir -ChildPath $outFileName
              Write-Output "Converting $srcFile to PDF. Saving to $outFile"
              $pres = $ppt.Presentations.Open($srcFile)
              $pres.SaveAs($outFile, $opt)
          }

      # Runs a set of commands using the runners shell
      - uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: ./bin/
